function objects = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  OBJECTS = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  OBJECTS = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  objects = importfile("C:\SEO Manchester Uni\Andrew Gilmore\Robert Pedley\IMC single cell neighbourhood analysis for muhammad\IMC single cell neighbourhood analysis for muhammad\Steinbock\objects.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Nov-2022 14:28:13

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 31);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Image", "Object", "SMA", "Vimentin", "Sox9", "panKeratin", "Fibronectin", "cKit", "CD45", "FoxP3", "CD4", "ECadherin", "CD68", "Collagen_6", "CD20", "CD8a", "Granzyme_B", "Ki67", "Collagen_1", "CD3", "CD45RO", "PDGFRa", "Histone_H3", "Ir", "Ir1", "area", "centroid0", "centroid1", "axis_major_length", "axis_minor_length", "eccentricity"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Image", "EmptyFieldRule", "auto");

% Import the data
objects = readtable(filename, opts);

end